import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react';
import path from 'path';
import { defineConfig } from 'vite';

/** ゲスト回答 UI。庁内と同じ FillForm を IIFE にまとめ、patchform-app/public へ出す。 */
export default defineConfig({
  plugins: [react(), tailwindcss()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  define: {
    'process.env.NODE_ENV': '"production"',
  },
  build: {
    outDir: path.resolve(__dirname, '../../../patchform-app/public'),
    emptyOutDir: false,
    cssCodeSplit: false,
    lib: {
      entry: path.resolve(__dirname, 'src/open-genai/patchform/guest/main.tsx'),
      name: 'PatchformGuest',
      formats: ['iife'],
      fileName: () => 'guest.js',
    },
    rollupOptions: {
      output: {
        banner: '/* generated by npm run build:patchform-guest — do not edit */',
        assetFileNames: (info) => (info.name?.endsWith('.css') ? 'guest.css' : '[name][extname]'),
      },
    },
  },
});
